config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :hearts
  resources :relationships
  resources :posts
  resources :lists_recipes
  get 'feed' => 'posts#index'

  post 'lists' => 'lists#create'

  resources :comments
  resources :reviews
  resources :convos
  resources :suggestions
  resources :tag_types
  resources :tags

  get 'categories' => 'tag_types#index'
  get 'about' => 'static_pages#about'
  get 'vision' => 'static_pages#vision'
  get 'help' => 'static_pages#help'
  get 'suggestion_added' => 'static_pages#suggestion_added'
  get 'community' => 'static_pages#community'
  get 'not_found' => 'static_pages#not_found'
  get 'going_ons' => 'static_pages#going_ons'
  get 'box' => 'static_pages#box'
  get 'search' => 'static_pages#generic_search'

  get 'following' => 'static_pages#following'
  get 'followers' => 'static_pages#followers'
  
  resources :groups
  resources :recipes do
    put 'star', on: :member
    put 'unstar', on: :member
  end

  resources :group_memberships
  resources :group_posts

  devise_for :members, :controllers => { :registrations => "registrations" }

  resources :members do   #|
    resources :lists #in lists_controller, member_name passed as params[:member_id]
  end

  devise_scope :member do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get 'register' => 'registrations#new'
    get 'edit_account' => 'devise/registrations#edit'
    get 'delete_account' => 'devise/registrations#destroy'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include MembersHelper
  include RecipesHelper #for add_to_analysis(...)

  def home
  end

  def about
  end

  def help
  end

  def vision
  end

  def community
    @groups = Group.last(4)
    @members = Member.last(8).reverse
  end

  def recipe_search
    @recipes = []
    if (params[:search].present?)
      tags = Tag.all
      tokenized_tags = params[:search].split(' ')
      tag_columns = tags.select { |e| tokenized_tags.include? e.name }
      tag_columns.each do |t|
       @recipes += t.recipes
      end
      @recipes = @recipes.uniq
      #TODO user analysis
      #columns = TagHits.columns.map {|c| c.name}
      #base_columns = columns.select { |i| !i.match(/percent$/) && i.match(/count$/) }
      #add_to_analysis(params[:search].split(' '), 2)
    else
      @recipes = []
    end
  end

  def post_search
    if (params[:search].present?)
      @posts = [] #Post.search(params[:search]).records.to_a
    else
      @posts = Post.all.reverse
      respond_with(@posts)
    end
  end

  def member_search
    if (params[:search].present?)
      token = params[:search]
      @members = []
      @members += Member.where('user_name LIKE ?', "%"+token + "%")
      @members += Member.where('email LIKE ?', "%"+token+"%")
      @members = @members.uniq
    else
      @members = []
    end
  end

  def generic_search
      @tags = ["whatsfordinner", "whatsforlunch", "lazycat", "nomnom", "Chinese"]
      @recipes = Recipe.last(8)
      @posts = Post.last(4)
      @groups = Group.last(4)
      @members = Member.last(8).reverse
  end

  def group_search
    if (params[:search].present?)
      @groups = Group.where('name LIKE ?', "%"+params[:search]+"%") #the percentages are postgres wildcards. O/w can do without but will exact match
    else
      @groups = []
    end
  end

  def suggestion_added
  end

  def not_found
  end

  def going_ons
   @activities = nil
  end

  def box
    if !member_signed_in?
    else
      @starred_list = StarredRecipeList.find_by_member_id(current_member.id).saved_recipes_array.split(",").map { |e| e.to_i }
      make_recommendation(current_member)
      rec_list = Recommendations.find_by_member_id(current_member.id).recs_list.split(',').map { |e| e.to_i }
      @recommended = []
      rec_list.each do |r|
        @recommended.push(Recipe.find(r))
      end
      @recent = []
      begin
        @list = current_member.recently_viewed_recipes.recently_viewed_list.split(",").map {|e| e.to_i }
        @list.each do |l|
          @recent.push(Recipe.find(l))
        end
      rescue
        logger.debug "StaticPages#box **Fatal: Could not find Member(#{current_member.id}).recently_viewed_recipes"
      end
    end
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_heart_build.html.erb
<% ddway = false %>
<div id="heart_form<%= recipe.id %>" style="float: left;">
<% if member_signed_in? %>
  <% if current_member.liked_recipes.include? recipe %>
    <% heart = current_member.hearts.select { |x| x.liked_recipe_id == recipe.id } %>
    <% if ddway ==  true  %>
      <%= link_to heart_path(heart), method: "DELETE", action: "destroy", remote: true do %>
        <%= image_tag("liked.png", :class => "width_15px")%><span class="down_6"><%= recipe.likers.count %></span>
      <% end %> 
    <% else %>
      <%= link_to "[UNHEART]", heart_path(heart), method: "DELETE", action: "destroy", remote: true %>
    <% end %>
  <% else %>
    <% if ddway == true %>
      <%= form_for(current_member.hearts.build(liker_id: current_member.id), remote: true) do |f| %>
        <%= f.hidden_field :liker_id, :value => current_member.id %>
        <%= f.hidden_field :liked_recipe_id, :value => recipe.id %>
        <%= image_submit_tag("empty_liked.png", :class => "width_15px") %><span class="down_6"><%= recipe.likers.count %></span>
      <% end %>
    <% else %>
      <%= form_for(current_member.hearts.build(liker_id: current_member.id), remote: true) do |f| %>
        <%= f.hidden_field :liker_id, :value => current_member.id %>
        <%= f.hidden_field :liked_recipe_id, :value => recipe.id %>
        <%= f.submit "[HEART]" %> <%= recipe.likers.count %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <button>[HEART]</button><%= recipe.likers.count %>
<% end %>
</div>

app/views/static_pages/_search_form.html.erb
<style>
ul#search_action_choices > li {
  list-style: none;
  display: inline-block;
}
form#static_search_form {
  width: 270px;
}
</style>

<div id="generic_search_search_bar" style="width:300px; max-width: 80%;">
  <div style="float: left; padding: 10px 10px 10px 10px;">
  Search
  </div>
  <div style="float: left;">
  <ul id="search_action_choices">
    <li><a href="#" onclick="choose_action('/search/recipes', this)">Recipes</a></li> |
    <li><a href="#" onclick="choose_action('/search/groups', this)" style="font-weight: bold;">Groups</a></li> |
    <li><a href="#" onclick="choose_action('/search/posts', this)">Posts</a></li> |
    <li><a href="#" onclick="choose_action('/search/members', this)">Members</a></li>
  </ul>
  
  <br>
  <div class="search" style="clear: both;"> 
    <form id="static_search_form" class="search-form" method="get" action="/search/groups" accept-charset="UTF-8">
      <div style="display:none">
        <input type="hidden" value="✓" name="utf8"></input>
      </div>
        <input id="search_params" type="text" placeholder="Something awesome!" name="search_params"></input>
        <button type="submit" class="search_bttn"><%= image_tag("search_black.png") %></button>
    </form>
  </div> 
  </div>
</div> 

<script>
function choose_action(action, element){
  var a = document.getElementById("search_action_choices").getElementsByTagName("a");
  for(var i = 0; i < a.length; i++){
    a[i].style.fontWeight= "normal";
  }
  element.style.fontWeight= "bold";
  var form = document.getElementById("static_search_form");
  form.action=action;
}
</script>

app/views/static_pages/box.html.erb
<style>

ul#tabs { list-style-type: none; margin: 30px 0 0 0; padding: 0 0 0.3em 0;}
ul#tabs li { display: inline; }
ul#tabs li a { color: #42454a; background-color: #dedbde; padding: 1.2em 1em 2em !important; border-radius: 8px;  text-decoration: none; }
ul#tabs li a:hover { background-color: #f1f0ee; }
ul#tabs li a.selected { color: #000; background-color: #f1f0ee; font-weight:bold; padding: 0.7em 0.3em 0.38em 0.3em; z-index: 1;}
div.tabContent { display: block; float: left; width: 100%; background-color: #f1f0ee; position: relative; top: -2px;}
div.tabContent.hide { display: none; }
div.tabContent > div {
  padding: 3em;
}

</style>

<%= link_to "[LISTS]", member_lists_path(current_member.user_name) %>

<script type="text/javascript">
function show_more(element){
  var currNode = element;
  var next = element.parentNode.getElementsByClassName("hidden")[0];
  next.style.visibility = "visible";
  currNode.style.visibility = "hidden";
}

function hide(element){
  element.parentNode.style.visibility = "hidden";
  element.parentNode.parentNode.getElementsByClassName("show_more")[0].style.visibility = "visible";
}

var tabLinks = new Array();
var contentDivs = new Array();

function init(){
  var tabListItems = document.getElementById('tabs').childNodes;
  for(var i = 0; i < tabListItems.length; i++){
    if (tabListItems[i].nodeName == "LI"){
      var tabLink = getFirstChildWithTagName(tabListItems[i], 'A');
      var id = getHash(tabLink.getAttribute('href'));
      tabLinks[id] = tabLink;
      contentDivs[id] = document.getElementById(id);
    }
  }
  var i = 0;
  for(var id in tabLinks){
    tabLinks[id].onclick = showTab;
    tabLinks[id].onfocus = function() {this.blur()};
    if (i == 0) tabLinks[id].className = 'selected';
    i++;
  }
  var i = 0;
  for(var id in contentDivs) {
    if (i != 0) contentDivs[id].className = 'tabContent hide';
    i++;
  }
}

function showTab(){
  var selectedId = getHash(this.getAttribute('href'));
  for(var id in contentDivs){
    if (id == selectedId){
      tabLinks[id].className = 'selected';
      contentDivs[id].className = 'tabContent';
    } else {
      tabLinks[id].className = '';
      contentDivs[id].className = 'tabContent hide';
    }
  }
  return false; //Stop browser following the link
}

function getFirstChildWithTagName(element, tagName){
  for(var i = 0; i < element.childNodes.length; i++){
    if (element.childNodes[i].nodeName == tagName) return element.childNodes[i];
  }
}

function getHash(url){
  var hashPos = url.lastIndexOf('#');
  return url.substring(hashPos + 1);
}
</script>

<div class="content_wrapper_main">
  <ul id="tabs">
      <li><a href="#page-1"><span>Your Box</span></a></li>
      <li><a href="#page-2"><span>Your Recipes</span></a></li>
      <li><a href="#page-3"><span>Liked/Saved</span></a></li>
      <li><a href="#page-4"><span>Reviewed</span></a></li>
      <li><a href="#page-5"><span>Recommendations</span></a></li>
  </ul>

  <div class="tabContent" id="page-1">
    <div>
    The box is used to store your own recipes, saved recipes, and keep track of recipes you like. In the future, you may also make notes and annotate recipe, and also keep track of what you've been making and doing. We hope this becomes a trusted cooking helper!
  
    -DDMM
    </div>
  </div>

  <div class="tabContent" id="page-2">
    <div>
      <h2>Your Recipes</h2>
      <% if member_signed_in? %>
       <%= render current_member.recipes %>
      <% end %>
    </div>
  </div>
  
  <div class="tabContent" id="page-3">
    <div>
      <h2>Liked Recipes</h2>
      <% if member_signed_in? %>
        <%= render current_member.liked_recipes %>
      <% end %>
    </div>
  </div>
  
  <div class="tabContent" id="page-4">
    <div>
      <h2>Reviewed Recipes</h2>
      <% if member_signed_in? %>
        <%= render partial: "reviews/review_brief", :as  => :review, :collection => current_member.reviews %>
      <% end %>
    </div>
  </div>
  
  <div class="tabContent" id="page-5">
    <div>
      <h2>Recommended Recipes</h2>
      <% if member_signed_in? %>
        <%= render @recommended %>
      <% end %>
    </div>
  </div>
  <% if member_signed_in? %>
  <div class="tabContent" id="page-6">
    <div>
      <h2>Recently Viewed Recipes</h2>
<%= render @recent %>
    </div>
  </div>
  <% end %>

</div>

<script>
init();
</script>

app/views/static_pages/community.html.erb
<div class="content_wrapper_main">

<div id="member_list" style="clear: both;">
  <h1>Some new members</h1>
  <div class="member_results" style="clear:both; padding-top: 10px;">
     <% if params["search"] != nil%>
       <span class="result_announcer">Results for <em><%= params["search"]%></em></span>
       <% if @members == [] %>
         <span class="result_announcer">No results for <em><%= params["search"]%></em></span>
       <% end %>
     <% else %>
     <% end %>
    
    <table style="clear: both;">
      <tbody>
        <% @members.each do |member| %>
          <tr>
            <td>
              <%= link_to member do %>
                <%= image_tag member.photo.url(:tiny_thumb), :class => "rounded_tiny_thumb"%>
                <span class="tiny_thumb_text"><%= member.user_name %></span>
                <span class="tiny_thumb_text"><%= member.first %> <%= member.last %></span>
                <span class="tiny_thumb_text"><%= member.occupation %></span></td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="group_list">
  <h1>Some Groups</h1>
  <% @groups.each do |group| %>
    <%= link_to group.name, group %><br>
  <% end %>
  <%= link_to new_group_path do %>
    <%= button_tag :class => "button_round_burnt_orange" do %>Create a new group!<% end %>
  <% end %>
</div>

</div>

app/views/static_pages/followers.html.erb
<div class="content_wrapper_main">
<% if member_signed_in? %>
  <%= render partial: "members/grid_item", :as => :member, :collection => current_member.following %>
<% else %>
  This is where your the members you follow are listed.
<% end %>
</div>

app/views/static_pages/following.html.erb
<div class="content_wrapper_main">
<% if member_signed_in? %>
  <%= render partial: "members/grid_item", :as => :member, :collection => current_member.following %>
<% else %>
  This is where the members you will follow are listed.
<% end %>
</div>

app/views/static_pages/generic_search.html.erb
<%= render 'search_form' %>

<div class="content_wrapper_main">
  <h1>Some Groups</h1>
  <% @groups.each do |group| %>
    <%= link_to group.name, group %>
  <% end %>
  
  <h1>Some Tags</h1>
  <% @tags.each do |tag| %>
    <%= link_to "/posts?utf8=✓&search=#{tag}" do %>
      <%= button_tag :class => "button_round_burnt_orange" do%><% tag %><% end %>
    <% end %>
  <% end %>
  
  <h1>Some Posts</h1>
  <% @posts.each do |post| %>
    <div class="post_indiv">
      <%= link_to post do %>
      <%= image_tag post.photo.url(:cropped_square_thumb) %>
      <% end %><br>
      <% if post.author %>
        <%= link_to post.author do %>
          <%= image_tag post.author.photo.url(:tiny_thumb), class: "rounded_tiny_thumb" %><%= post.author.user_name %>
        <% end %><br>
      <% else %>
        <%= image_tag("missing/tiny_thumb.png", class: "rounded_tiny_thumb") %>Anonymous
      <% end %>
      <div id="show_tags">
      <% tags = destringify_tags(post.s_tags) %>
      <% if tags != nil && tags != [] %>
        Tags:
        <% tags.each do |tag| %>
          <%= link_to tag, "/posts?utf8=✓&search=#{tag}", :class => "tag_search" %>
        <% end %>
      <% end %>
      </div>
      <%= post.post_text %><br>
      <% if current_member.try(:id) == post.author_id %>
        <%= link_to edit_post_path(post) do %>
          <%= button_tag :class=> "button_round_blue" do %>Edit<% end %>
        <% end %>
        <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= button_tag :class => "button_round_blue" do %>Remove Post<% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  
  <h1>Some Recipes</h1>
  <% @recipes.each do |recipe| %>
    <div class="search_result_recipe">
      <%= link_to recipe do %>
      <%= image_tag recipe.main_photo.url(:cropped_square_thumb), :class => "square_170" %><br>
      <%= link_to recipe.name, recipe, class: "search_result_recipe_name" %><br>
      <% end %>
      <%= render partial: "recipes/rating_stars", locals: { recipe: recipe } %>
      <%= render partial: "heart_build", locals: { recipe: recipe } %>
      <%= "Servings: #{recipe.servings}" %><br>
      <%= "Prep time: #{recipe.prep_time}" %>min<br>
      <%= " Cook time: #{recipe.cook_time} min" %>
      <br>
      <div class="search_result_recipe_credit">
        <% if recipe.author != nil %>
          <%= link_to recipe.author do %>
            <%= image_tag recipe.author.photo.url(:tiny_thumb), class: "rounded_tiny_thumb" %>
          <% end %>
          <span class="search_result_credit_text"><%= link_to recipe.author.user_name, recipe.author, class: "search_result_recipe_author" %></span>
        <% else %>
          <%= image_tag("missing/tiny_thumb.png") %> <span class="search_result_credit_text">anonymous</span>
        <% end %>
      </div>
      <div id="show_tags">
      <% if recipe.s_tags != nil %>
        Tags:
        <% recipe.s_tags.split(',').each do |tag| %>
          <%= link_to tag, "/recipes?utf8=✓&search=#{tag}", :class => "tag_search" %>
        <% end %>
      <% end %>
      </div>
    </div>
  <% end %>
  
  
  <h1>Some new members</h1>
  <div class="member_results" style="clear:both; padding-top: 10px;">
     <% if params["search"] != nil%>
       <span class="result_announcer">Results for <em><%= params["search"]%></em></span>
       <% if @members == [] %>
         <span class="result_announcer">No results for <em><%= params["search"]%></em></span>
       <% end %>
     <% else %>
     <% end %>
  
    <table style="clear: both;">
      <tbody>
        <% @members.each do |member| %>
          <tr>
            <td>
              <%= link_to member do %>
                <%= image_tag member.photo.url(:tiny_thumb), :class => "rounded_tiny_thumb"%>
                <span class="tiny_thumb_text"><%= member.user_name %></span>
                <span class="tiny_thumb_text"><%= member.first %> <%= member.last %></span>
                <span class="tiny_thumb_text"><%= member.occupation %></span></td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/static_pages/going_ons.html.erb
<div class="content_wrapper_main">
Hi there, lot's going on.
</div>

app/views/static_pages/group_search.html.erb
<div class="content_wrapper_main">

  <div style="clear: both;">
  <h1>Some Groups</h1>
  <% @groups.each do |group| %>
    <%= link_to group.name, group %>
  <% end %>
  </div>

</div>
<script>
choose_action('/search/groups', document.getElementById("search_action_choices").getElementsByTagName('a')[1])
</script>

app/views/static_pages/home.html.erb
<div class="content_wrapper_main">
  <div class="popular-recipe-categories">
     Popular Categories: <br>
     <%= link_to "/recipes?utf8=✓&search=Chinese" do %>
       <%= button_tag :class => "button_round_burnt_orange" do %>Chinese<%end %>
    <% end %>
     <%= link_to "/recipes?utf8=✓&search=dim+sum" do %>
       <%= button_tag :class => "button_round_burnt_orange" do %>Dim Sum<%end %>
    <% end %>
     <%= link_to "/recipes?utf8=✓&search=Easy" do %>
       <%= button_tag :class => "button_round_burnt_orange" do %>Easy<%end %>
    <% end %>
  </div>
  
  <div id="hero-box">
    <div class="logo"><%= image_tag("ddmimi-rabbit.png") %></div>
    <div>TUZI CHEF</div>
    <div id="lang-tuzi">兔子 thỏ</div>
    <div id="lang-tuzi">토끼 ウサギ</div>
    <div id="hero-text">COMING</div>
    <div id="hero-text"> SOON</div>
  </div>
  
</div>

app/views/static_pages/not_found.html.erb
<div class="content_wrapper_main">
You've come to the end of the rabbit hole.<br>
This entity was not found.<br>
It has been deleted or has never existed. :P<br>
Or, you don't have sufficient permission to edit.
</div>

app/views/static_pages/post_search.html.erb
<script>
choose_action('/search/posts', document.getElementById("search_action_choices").getElementsByTagName('a')[2])
</script>
<div class="content_wrapper_main">
  <h1>Some Posts</h1>
  <% @posts.each do |post| %>
    <div class="post_indiv">
      <%= link_to post do %>
      <%= image_tag post.photo.url(:cropped_square_thumb) %>
      <% end %><br>
      <% if post.author %>
        <%= link_to post.author do %>
          <%= image_tag post.author.photo.url(:tiny_thumb), class: "rounded_tiny_thumb" %><%= post.author.user_name %>
        <% end %><br>
      <% else %>
        <%= image_tag("missing/tiny_thumb.png", class: "rounded_tiny_thumb") %>Anonymous
      <% end %>
      <div id="show_tags"> 
      <% tags = destringify_tags(post.s_tags) %>
      <% if tags != nil && tags != [] %>
        Tags:
        <% tags.each do |tag| %>
          <%= link_to tag, "/posts?utf8=✓&search=#{tag}", :class => "tag_search" %>
        <% end %>
      <% end %>
      </div>
      <%= post.post_text %><br>
      <% if current_member.try(:id) == post.author_id %>
        <%= link_to edit_post_path(post) do %>
          <%= button_tag :class=> "button_round_blue" do %>Edit<% end %>
        <% end %>
        <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= button_tag :class => "button_round_blue" do %>Remove Post<% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/static_pages/terms_and_privacy.html.erb
<div class="content_wrapper_main">
  <h3>We take your privacy very seriously.</h3>
  <p>
  Your password is encrypted. We do not actually handle the raw passwords. Maybe no one actually does. 
  </p>
</div>

app/views/static_pages/vision.html.erb
<div class="content_wrapper_main">
  <h1>Our Vision</h1>
  <p>
  Our vision is wide, all encompassing, and exciting!
  </p>
  <p>
  We are working on implementing a lot of functionality. As soon as we test them thoroughly locally, we slowly roll them into the site. Sometimes something may break. If it does, please let us know through email or text and we will resolve the problems. Thanks for helping us in this super important task of testing our site!
  </p>
  Best,<br>
  DDMM
  <br>
  <%= image_tag("beet.png") %>
</div>