config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :hearts
  resources :relationships
  resources :posts
  resources :lists_recipes
  get 'feed' => 'posts#index'

  post 'lists' => 'lists#create'

  resources :comments
  resources :reviews
  resources :convos
  resources :suggestions
  resources :tag_types
  resources :tags

  get 'categories' => 'tag_types#index'
  get 'about' => 'static_pages#about'
  get 'vision' => 'static_pages#vision'
  get 'help' => 'static_pages#help'
  get 'suggestion_added' => 'static_pages#suggestion_added'
  get 'community' => 'static_pages#community'
  get 'not_found' => 'static_pages#not_found'
  get 'going_ons' => 'static_pages#going_ons'
  get 'box' => 'static_pages#box'
  get 'search' => 'static_pages#generic_search'

  get 'following' => 'static_pages#following'
  get 'followers' => 'static_pages#followers'
  
  resources :groups
  resources :recipes do
    put 'star', on: :member
    put 'unstar', on: :member
  end

  resources :group_memberships
  resources :group_posts

  devise_for :members, :controllers => { :registrations => "registrations" }

  resources :members do   #|
    resources :lists #in lists_controller, member_name passed as params[:member_id]
  end

  devise_scope :member do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get 'register' => 'registrations#new'
    get 'edit_account' => 'devise/registrations#edit'
    get 'delete_account' => 'devise/registrations#destroy'
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :owner, :class_name => "Group"
  has_many :group_memberships, foreign_key: "joined_group_id"
  has_many :members, :through => :group_memberships
  has_and_belongs_to_many :posts
  has_many :group_posts
  has_many :posts, through: :group_posts
  validates :name, :uniqueness => true
  def slug
    name.downcase.gsub(" ","-")
  end

  def self.parse_params(params)
    params
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include NewsFeedHelper

  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :signed_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :can_edit, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @groups = Group.all
    if (params[:search].present?)
      @groups = Group.where('name LIKE ?', "%"+params[:search]+"%") #the percentages are postgres wildcards. O/w can do without but will exact match
    else
      @groups = Group.all.reverse
      respond_with(@groups)
    end
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

#  def edit
#  end

  def create
    @group = Group.new(group_params)
    if @group.save
      xml_builder = ::Builder::XmlMarkup.new
      mass_str = xml_builder.p { |xml|
        xml.a(current_member.user_name, 'href' => member_path(current_member))
        xml.em(" just created the group ")
        xml.a(@group.name, 'href' => group_path(@group))
      }
      mass_feed_push(current_member.id, mass_str)
    end
    respond_with(@group)
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }     
      end
    end
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:owner_id, :name, :description)
  end
  def signed_in
    if !member_signed_in?
      redirect_to login_path
    end
  end
  def can_edit
    if !(current_member.id == @group.owner_id || current_member.admin == true)
      redirect_to not_found_path
    end
  end

end

app/views/groups/_build_join.html.erb
<div id="membership_form<%= group.id %>">
Members: <%= group.members.count %><br>
Group Posts: <%= group.posts.count %><br>
<% if member_signed_in? %>
  <% if current_member.joined_groups.include? group %>
    <%= form_for(current_member.group_memberships.find_by(:joined_group_id => group.id), method: "DELETE", action: "destroy") do |f| %>
      <%= f.submit "UNJOIN GROUP", :class => "button_round_burnt_orange" %>
    <% end %>
  <% else %>
    <%= form_for(current_member.group_memberships.build(:joined_group_id => group.id)) do |f| %>
      <%= f.hidden_field :joined_group_id, value: group.id %>
      <%= f.hidden_field :member_id, value: current_member.id %>
      <%= f.submit "JOIN GROUP", :class => "button_round_burnt_orange" %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to "Sign in to join group!", members_login_path %>
<% end %>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Choose group name. Must be unique" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :owner_id, :value => current_member.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="content_wrapper_main">
  <h1>Create your new group. You must have a unique name</h1>
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<div class="content_wrapper_main">
<% @groups.each do |group| %>
  <%= link_to group.name, group %>
<% end %>
</div>

app/views/groups/new.html.erb
<div class="content_wrapper_main">
  <h1>Create your new group. You must have a unique name</h1>
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<div class="side_bar pull_left"> 
  <h1><%=@group.name %></h1>
  <h2><%= @group.description %></h2>
  <%= "want to join?" %><br>
  <%= render partial:'groups/build_join', :locals => {group: @group} %>
</div>
<div class="content_wrapper_main">
  <% @group.posts.each do |post| %>
    <div class="post_indiv">
    <%= link_to post do %>
    <%= image_tag post.photo.url(:cropped_square_thumb) %>
    <% end %><br>
    <% if post.author %>
      <%= link_to post.author do %>
        <%= image_tag post.author.photo.url(:tiny_thumb), class: "rounded_tiny_thumb" %>
          <%= post.author.user_name %>
      <% end %><br>
    <% else %>
      <%= image_tag("missing/tiny_thumb.png", class: "rounded_tiny_thumb") %>Anonymous
    <% end %>
    <div id="show_tags">
    <% if post.s_tags != nil %>
      Tags:
      <% post.s_tags.split(',').each do |tag| %>
        <%= link_to tag, "/posts?utf8=✓&search=#{tag}", :class => "tag_search" %>
      <% end %>
    <% end %>
    </div>
    <%= post.post_text %><br>
    <% if current_member.try(:id) == post.author_id %>
      <%= link_to edit_post_path(post) do %>
        <%= button_tag :class=> "button_round_blue" do %>Edit<% end %>
      <% end %>
      <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= button_tag :class => "button_round_blue" do %>Remove Post<% end %>
      <% end %>
    <% end %>
    </div>
  <% end %>
</div>