config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :hearts
  resources :relationships
  resources :posts
  resources :lists_recipes
  get 'feed' => 'posts#index'

  post 'lists' => 'lists#create'

  resources :comments
  resources :reviews
  resources :convos
  resources :suggestions
  resources :tag_types
  resources :tags

  get 'categories' => 'tag_types#index'
  get 'about' => 'static_pages#about'
  get 'vision' => 'static_pages#vision'
  get 'help' => 'static_pages#help'
  get 'suggestion_added' => 'static_pages#suggestion_added'
  get 'community' => 'static_pages#community'
  get 'not_found' => 'static_pages#not_found'
  get 'going_ons' => 'static_pages#going_ons'
  get 'box' => 'static_pages#box'
  get 'search' => 'static_pages#generic_search'

  get 'following' => 'static_pages#following'
  get 'followers' => 'static_pages#followers'
  
  resources :groups
  resources :recipes do
    put 'star', on: :member
    put 'unstar', on: :member
  end

  resources :group_memberships
  resources :group_posts

  devise_for :members, :controllers => { :registrations => "registrations" }

  resources :members do   #|
    resources :lists #in lists_controller, member_name passed as params[:member_id]
  end

  devise_scope :member do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get 'register' => 'registrations#new'
    get 'edit_account' => 'devise/registrations#edit'
    get 'delete_account' => 'devise/registrations#destroy'
  end

end

app/controllers/tag_types_controller.rb
class TagTypesController < ApplicationController
  before_action :set_tag_type, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:edit, :new, :update, :destroy, :create]
  respond_to :html

  def index
    @tag_types = TagType.all
    respond_with(@tag_types)
  end

  def show
    respond_with(@tag_type)
  end

  def new
    if member_signed_in? && current_member.admin
      @tag_type = TagType.new
      respond_with(@tag_type)
    else
      redirect_to root_url
    end
  end

  def edit
    if !member_signed_in? || current_member.admin == false
      redirect_to root_url
    end
  end

  def create
    if member_signed_in? && current_member.admin
      @tag_type = TagType.new(tag_type_params)  
      @tag_type.save
      respond_with(@tag_type)
    else
      redirect_to root_url
    end
  end

  def update
    if member_signed_in? && current_member.admin
      @tag_type.update(tag_type_params)
      respond_with(@tag_type)
    else
      redirect_to root_url
    end
  end

  def destroy
    if member_signed_in? && current_member.admin
      @tag_type.destroy
      respond_with(@tag_type)
    else
      redirect_to root_url
    end
  end

  private
    def set_tag_type
      @tag_type = TagType.find(params[:id])
    end

    def tag_type_params
      params.require(:tag_type).permit(:name, :description)
    end

    def check_admin
      if !(member_signed_in? && current_member.admin)
        redirect_to root_url
      end
    end
end

app/helpers/tag_types_helper.rb
module TagTypesHelper
end

app/views/tag_types/_form.html.erb
<%= form_for(@tag_type) do |f| %>
  <% if @tag_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_type.errors.count, "error") %> prohibited this tag_type from being saved:</h2>

      <ul>
      <% @tag_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tag_types/edit.html.erb
<div class="content_wrapper_main">
  <h1>Editing tag_type</h1>
  <%= render 'form' %>
  <%= link_to 'Show', @tag_type %> |
  <%= link_to 'Back', tag_types_path %>
</div>

app/views/tag_types/index.html.erb
<div class="content_wrapper_main">
  <h1>Categories</h1>
  <% @tag_types.each do |tag_type| %>
  <div class="category">
    <div class="tag_type_name">
    <%= tag_type.name %>
    <%= link_to "Edit", edit_tag_type_path(tag_type) %> |
    <%= link_to tag_type, :method => "DELETE", :action => "destroy", data: { confirm: "Are you sure? This cannot be undone." } do %>
          Delete
        <% end %>

    </div>
    <% tag_type.tags.each do |tag| %>
      <%= link_to tag.name %>
      <% if current_member.try(:admin) %>
        <%= link_to "Edit", edit_tag_path(tag) %> |
        <%= link_to tag, :method => "DELETE", :action => "destroy", data: { confirm: "Are you sure? This cannot be undone." } do %>
          Delete
        <% end %>
      <% end %>
      <br>
    <% end %>
    <br>
  </div>
  <% end %>
  <%  if current_member.try(:admin) %>
    <%= link_to 'New Tag Type', new_tag_type_path %> | <%= link_to "New Tag", new_tag_path %>
  <% end %>
</div>

app/views/tag_types/new.html.erb
<div class="content_wrapper_main">
  <h1>Create a New Category</h1>
  <%= render 'form' %>
  <%= link_to 'Back', tag_types_path %>
</div>

app/views/tag_types/show.html.erb
<div class="content_wrapper_main">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @tag_type.name %>
  </p>
  <%= link_to 'Edit', edit_tag_type_path(@tag_type) %> |
  <%= link_to 'Back', tag_types_path %>
</div>